<img src=https://www.icesi.edu.co/wp-content/uploads/2024/10/ICESI_logo_prin_descriptor_RGB_NEGATIVO_0924-768x395.png width="300" height="200" align="center">

#**<big><big>Matemáticas Aplicadas II</big></big><br><small>Depto. Ciencias Físicas y Exactas/ Facultad de Ingeniería, Diseño y Ciencias Aplicadas</small><br><small>_*Cuaderno 4*_ (Vectores y Matrices). </small>**

1. **Lectura sugerida del texto de Boyd. Introduction to Applied Linear Algebra:Vectors, Matrices, and Least Squares (2018)**:  Capítulos 1 (1.1 - 1.4), 3 (3-1, 3.2, 3.4), 6 (6.1. - 6.4), 7 y sección 10.1.

**<u>Agenda</u>**
*Vectores, matrices, operaciones con matrices y ejemplos de aplicación*


# Vectores

> Un vector se puede considerar como un arreglo finito ordenado de números. En la entrega III usted trabajará en profundidad con el concepto de vector, sus propiedades, sus operaciones y algunas de sus aplicaciones.



# Operaciones con Vectores

## 1. Suma de vectores
Sea $\vec{u}, \vec{v} \in \mathbb{R}^n$.  
Si  
$$
\vec{u} = (u_1, u_2, \dots, u_n), \quad
\vec{v} = (v_1, v_2, \dots, v_n),
$$
entonces la **suma** se define como
$$
\vec{u} + \vec{v} = (u_1 + v_1, \; u_2 + v_2, \; \dots, \; u_n + v_n).
$$

**Interpretación geométrica:**  
La suma de vectores corresponde a colocar el segundo vector a continuación del primero (regla del paralelogramo). El vector resultante va desde el origen hasta el vértice opuesto del paralelogramo.

---

## 2. Producto por un escalar
Sea $\alpha \in \mathbb{R}$ y $\vec{u} \in \mathbb{R}^n$.  
Si
$$
\vec{u} = (u_1, u_2, \dots, u_n),
$$
entonces el **producto por un escalar** se define como
$$
\alpha \cdot \vec{u} = (\alpha u_1, \; \alpha u_2, \; \dots, \; \alpha u_n).
$$

**Interpretación geométrica:**  
Multiplicar un vector por un escalar tiene varios efectos. Interactue con el applet de Geogebra para saber bajo que condiciones el vector $\vec{w}  = \alpha \cdot \vec{u}$ se alarga o se acorta (si $|\alpha| $ se alarga, si $ |\alpha| $ se acorta), y si $\alpha $ además invierte su dirección.

In [ ]:
#@title Producto por un escalar y suma de vectores

import IPython.display as IP

iframe = IP.IFrame(
  src="https://www.geogebra.org/classic/",
  width="1020px",
  height="480px"
  )

IP.display_html(iframe)

# Ejemplos

### Ejemplo 1: en $\mathbb{R}^2$
Sean
$$
\vec{u} = (2, 1), \quad \vec{v} = (-1, 3).
$$

- **Suma:**
$$
\vec{u} + \vec{v} = (2 + (-1), \; 1 + 3) = (1, 4).
$$

- **Producto por escalar:**  
Con $\alpha = 2$:
$$
2 \cdot \vec{u} = (2 \cdot 2, \; 2 \cdot 1) = (4, 2).
$$

Geométricamente, $\vec{u} + \vec{v}$ es la diagonal del paralelogramo formado por $\vec{u}$ y $\vec{v}$.  
El vector $2\vec{u}$ es $\vec{u}$ estirado al doble de su longitud.

---

### Ejemplo 2: en $\mathbb{R}^3$
Sean
$$
\vec{a} = (1, 0, -2), \quad \vec{b} = (3, -1, 4).
$$

- **Suma:**
$$
\vec{a} + \vec{b} = (1 + 3, \; 0 + (-1), \; -2 + 4) = (4, -1, 2).
$$

- **Producto por escalar:**  
Con $\alpha = -\tfrac{1}{2}$:
$$
-\tfrac{1}{2} \cdot \vec{b} = \left(-\tfrac{1}{2} \cdot 3, \; -\tfrac{1}{2} \cdot (-1), \; -\tfrac{1}{2} \cdot 4 \right) = \left(-\tfrac{3}{2}, \tfrac{1}{2}, -2\right).
$$

In [ ]:
#@title Operaciones con vectores

import IPython.display as IP

iframe = IP.IFrame(
  src="https://www.geogebra.org/m/tKGYbk7J",
  width="1020px",
  height="480px"
  )

IP.display_html(iframe)

# Vector unitario

## Definición
Un **vector unitario** es aquel cuya **longitud o norma** es igual a 1.  

Si $\vec{v} \in \mathbb{R}^n$, su norma se define como
$$
\|\vec{v}\| = \sqrt{v_1^2 + v_2^2 + \cdots + v_n^2}.
$$

Entonces, $\vec{u}$ es un vector unitario si
$$
\|\vec{u}\| = 1.
$$

---

## Construcción de un vector unitario
Dado un vector $\vec{v} \neq \vec{0}$, podemos obtener un vector unitario en su misma dirección dividiendo entre su norma:
$$
\vec{u} = \frac{\vec{v}}{\|\vec{v}\|}.
$$

---

## Ejemplos

### Ejemplo 1: en $\mathbb{R}^2$
Sea
$$
\vec{v} = (3,4).
$$

Su norma es
$$
\|\vec{v}\| = \sqrt{3^2 + 4^2} = \sqrt{9+16} = \sqrt{25} = 5.
$$

El vector unitario en la dirección de $\vec{v}$ es
$$
\vec{u} = \frac{1}{5}(3,4) = \left(\tfrac{3}{5}, \tfrac{4}{5}\right).
$$

---

### Ejemplo 2: en $\mathbb{R}^3$
Sea
$$
\vec{w} = (2,-1,2).
$$

Su norma es
$$
\|\vec{w}\| = \sqrt{2^2 + (-1)^2 + 2^2} = \sqrt{4+1+4} = \sqrt{9} = 3.
$$

El vector unitario en la dirección de $\vec{w}$ es
$$
\vec{u} = \frac{1}{3}(2,-1,2) = \left(\tfrac{2}{3}, -\tfrac{1}{3}, \tfrac{2}{3}\right).
$$

---

## Observación
- Todo vector no nulo puede transformarse en un vector unitario.  
- En $\mathbb{R}^2$, los vectores unitarios se encuentran en el **círculo unitario** $x^2+y^2=1$.  
- En $\mathbb{R}^3$, se encuentran en la **esfera unitaria** $x^2+y^2+z^2=1$.


# Combinación lineal de vectores

## Definición
Sean $\vec{v}_1, \vec{v}_2, \dots, \vec{v}_k \in \mathbb{R}^n$ y sean $\alpha_1, \alpha_2, \dots, \alpha_k \in \mathbb{R}$ (escalares).  

Se dice que el vector $\vec{w} \in \mathbb{R}^n$ es una **combinación lineal** de $\vec{v}_1, \vec{v}_2, \dots, \vec{v}_k$ si existen escalares $\alpha_1, \alpha_2, \dots, \alpha_k$ tales que:
$$
\vec{w} = \alpha_1 \vec{v}_1 + \alpha_2 \vec{v}_2 + \cdots + \alpha_k \vec{v}_k.
$$

---

# Ejemplos

### Ejemplo 1: en $\mathbb{R}^2$
Sean
$$
\vec{v}_1 = (1,2), \quad \vec{v}_2 = (3,-1).
$$

Tomemos los escalares $\alpha_1 = 2$, $\alpha_2 = -1$:  
$$
\vec{w} = 2\vec{v}_1 - \vec{v}_2 = 2(1,2) - (3,-1).
$$

Cálculo coordenada a coordenada:  
$$
\vec{w} = (2 \cdot 1, \; 2 \cdot 2) - (3, -1) = (2, 4) - (3, -1) = (2-3, 4 - (-1)) = (-1, 5).
$$

---

### Ejemplo 2: en $\mathbb{R}^3$
Sean
$$
\vec{v}_1 = (1,0,0), \quad \vec{v}_2 = (0,1,0), \quad \vec{v}_3 = (0,0,1).
$$

Estos son los vectores **canónicos** de $\mathbb{R}^3$.  

Tomemos $\alpha_1 = 2, \; \alpha_2 = -1, \; \alpha_3 = 3$:  
$$
\vec{w} = 2\vec{v}_1 - \vec{v}_2 + 3\vec{v}_3.
$$

Cálculo:  
$$
\vec{w} = 2(1,0,0) + (-1)(0,1,0) + 3(0,0,1) = (2,0,0) + (0,-1,0) + (0,0,3).
$$
$$
\vec{w} = (2,-1,3).
$$

---

## Observación
El conjunto de todas las combinaciones lineales de un conjunto de vectores se llama **subespacio generado** o **gen**.  
Por ejemplo:  
- $\operatorname{gen}\{(1,2),(3,-1)\}$ es una recta o el plano completo, según si los vectores son paralelos o no.  
- $\operatorname{gen}\{(1,0,0),(0,1,0),(0,0,1)\} = \mathbb{R}^3$.


#Matrices

> Antes mencionamos que la descripción matemática de ciertos fenómenos del mundo real requiere de una colección de números, y que tales situaciones se abstraen en el concepto de  vector. Ahora, vamos a construir otro objeto matemático compuesto por vectores para describir otras situaciones que involucran por ejemplo imágenes o grafos entre otros.

Las matrices generalmente se denotan con letras mayúsculas
rodeados por corchetes o paréntesis,

$$A=\left[\begin{array}{rrrr}
1.1&0.1&-0.5&100&1\\
0.0&0.2&-0.2&10&2\\
3.6&0.4&-0.1&1&3\\
7.2&0.8&0.0&0.1&4
\end{array}\right].$$


Los elementos (o entradas) de una matriz son los valores en el arreglo. El tamaño (también llamado dimensión) de una matriz viene dado por el número de vectores fila y columna que contiene. La matriz $A$ de arriba, por ejemplo, tiene  cuatro vectores fila y cinco vectores columna. Diremos que $A$ es una matriz $4\times 5$. Una matriz con $m$ filas y $n$ columnas tiene tamaño $m\times n$, se puede decir que pertenece a $\mathbb{R}^{m\times n}$.

# Generalidades



1.   Los elementos (o entradas o coeficientes) de una matriz son los valores del arreglo.
2. El elemento $i,j$ de la matriz, denotado $A_{ij}$ es el valor en la $i-$ésima fila y la $j-$ésima columna,

3. Dos matrices son iguales si tienen el mismo tamaño y las entradas correspondientes son todas iguales.
4. *Matrices cuadradas, altas y anchas*. Una matriz cuadrada tiene el mismo número de filas y columnas $(m=n)$. Se dice que una matriz cuadrada de tamaño $n\times n$ es de orden $n$. Una *matriz alta* tiene más filas que columnas (tamaño $m\times n$ con $m > n$). Una *matriz ancha* tiene más
columnas que filas (tamaño $m\times n$ con $n > m$)
5. *Vectores columna y fila*. Un $n-$vector se puede interpretar como una matriz $n\times 1$. Una matriz con
solo una fila, es decir, con tamaño $1\times n$, se llama vector fila.



*Representación matricial de una colección de vectores*  Las matrices se utilizan con mucha frecuencia
como una forma compacta de dar un conjunto de vectores indexados del mismo tamaño. Por ejemplo,
si $x_1,..., x_N$ son $n-$vectores que dan los $n$ valores característicos para cada uno de los $N$ objetos o registros, entonces
puede reunirlos todos en una matriz $n\times N$:

$$X=[x_1 \; x_2 \cdots x_n],$$

frecuentemente denominada *matriz de datos* o *matriz de atributos*. Su $j-$ésima columna es el vector de $n-$características para el $j-$ésimo objeto o registro, la $i-$ésima fila de la matriz de datos $X$ es un vector  fila cuyas entradas son los valores de la $i-$ésima
característica a través de los objetos o registros.

*Ejemplo (Matriz de representación de un grafo)*.  Una relación $R$ se puede ver como un gráfico dirigido, con nodos (o vértices) etiquetados $1,...,n$, y una arista dirigida de $j$ a $i$ para cada $(i,j)$. Esto se dibuja típicamente con un *grafo*, con flechas que indican la dirección de la arista, como se muestra en la figura 6.1 del texto de Boyd, para una relación sobre 4 objetos:

$$R = \{(1, 2), (1, 3), (2, 1), (2, 4), (3, 4), (4, 1)\} $$

En general, una relación $R$ sobre el conjunto $ \{1, 2, ...,n\} $ se puede representar con una matriz $A$ de $n\times n$ cuyas componentes vienen dadas  por

$$A_{ij}=\begin{cases}
1, & \text{ si } (i,j)\in R \\
0, & \text{ si } (i,j)\not\in R\end{cases}$$

Esta matriz se llama *matriz de adyacencia* asociada con el grafo. Dibujemos la matriz de adyacencia de la relación $R$.

*Ejemplo (Matriz de datos de un grafo)*. Una colección de $n-$vectores, por ejemplo,  $n-$vectores de atributos asociados con $N$ objetos o personas, se pueden describir como una matriz de $n\times N$ cuyas $N$ columnas son los vectores. También es común describir esta colección de vectores utilizando la transpuesta de esa matriz. En ese caso, damos los vectores como una matriz $X$ de $N\times n$. Su $i-$ésima fila es $x^T_i$, la transpuesta del $i-$ésimo vector. Su $j-$ésima columna da el valor de la $j-$ésima entrada (o atributo) en la colección de $N$ vectores. Cuándo
un autor se refiere a una matriz de datos o matriz de atributos, por lo general se puede determinar
del contexto (por ejemplo, sus dimensiones) si se refieren a la matriz de datos organizados por filas o columnas.

**Matrices Cero e Identidad.**

*Matriz cero*. Una matriz cero es una matriz con todos los elementos iguales a cero. La matriz cero de tamaño $m\times n$ a veces se escribe como $0_{m\times n}$, pero por lo general una matriz cero se denota solo $0$. En este caso, el tamaño de la matriz cero debe determinarse a partir del contexto.

*Matriz identidad*. Una matriz  identidad es otra matriz
cuadrada. Sus elementos diagonales, es decir, aquellos con índices de fila y columna iguales, son
todos iguales a uno, y sus elementos fuera de la diagonal (aquellos con índices fila y columna desiguales) son cero. Las matrices  identidad se denotan con la letra $I$ y se define por:

$$I_{ij}=\begin{cases}
1, & \text{ si } i=j \\
0, & \text{ si } i\not= j\end{cases}$$

*Matrices dispersas*. Se dice que una matriz $A$ es dispersa si muchas de sus entradas son cero. Su patrón de dispersión es el conjunto de índices $(i, j)$ para los cuales $A_{ij} \not= 0$. El número de ceros de una matriz dispersa $A$ es el número de entradas en su patrón de dispersión y se denota como $nnz(A)$.   Las densidades, $nnz(A)=mn$, de las matrices dispersas que surgen en las aplicaciones suelen ser pequeñas, como de orden $10^{-2}$ o $10^{-4}$.

*Matrices diagonales*. Una matriz $A$ cuadrada $n\times n$ es diagonal si $A_{ij} = 0$ para $i \not= j$. (Las entradas de una matriz con $i = j$ se denominan entradas diagonales; las que tienen $i \not= j$ son sus entradas fuera de la diagonal.). Ejemplos de matrices diagonales que ya hemos visto son cuadradas matrices cero y matrices identidad.

#Operaciones con matrices

*Matriz transpuesta.* Si $A$ es una matriz $m\times n$, su transpuesta, denotada $A^T$ (o a veces $A'$ o $A^*$), es la
matriz de $n\times m$ dada por $(A^T)_{ij} = A_{ji}$. En otras palabras, las filas y columnas de $A$ son
transpuestas en $A^T$.

*Producto de una matriz por un escalar*. La multiplicación escalar de matrices se define de manera similar a la de vectores, y es hecha multiplicando cada elemento de la matriz por el escalar.

*Suma de matrices*. Similarmente la suma de matrices del mismo tamaño se hace componente a componente, esto es, si $A=(A)_{ij}$ y $B=(B)_{ij}$ entonces $$C=(C)_{ij}=(A)_{ij}+(B)_{ij} $$


*Producto matriz-vector*. Si A es una matriz $m\times n$ y $x$ es un $n-$vector, entonces el producto matriz-vector $y = Ax$ es el $m-$vector $y$ con elementos

$$ y_i = \sum_{k=1}^n A_{ik}x_k=A_{i1}x_1+...+A_{in}x_n.,\quad i=1,...,m.$$

*Producto matriz-matriz*. Es posible multiplicar dos matrices $A$ y $B$ usando la multiplicación de matrices. siempre que sus dimensiones sean compatibles, lo que significa que elnúmero de columnas de $A$ es igual al número de filas de $B$. Supongamos que $A$ y $B$ son compatibles, por ejemplo, $A$ tiene tamaño $m\times p$ y $B$ tiene tamaño $p\times n$. Entonces la matriz del producto $C = AB$ es la matriz $m\times n$ con elementos

$$C_{ij}=\sum_{k=1}^? A_{ik}B_{kj}=A_{i1}B_{1j}+...+A_{ip}B_{pj}.,\quad i=1,...,m,\quad j=1,...,n.$$


In [ ]:
import numpy as np

# Define matrix A
A = np.array([[2, 4],
              [5, -6]])
print('Matrix A = \n', A)

# Transpose of matrix A
At = A.transpose()
print('\nTranspose of Matrix A = \n', At)

# Scalar multiplication
c = 5
cA = np.multiply(A, c)
print('\nScalar multiplication cA = \n', cA)

# Define matrix B
B = np.array([[9, -3],
              [3, 6]])
print('\nMatrix B = \n', B)

# Matrix addition
S = A + B
print('\nMatrix sum S = A + B = \n', S)

# Matrix multiplication (dot product)
P = A.dot(B)
print('\nMatrix product P = A * B = \n', P)

# Standard matrix multiplication
Q = np.matmul(A, B)
print('\nStandard matrix product Q = A @ B = \n', Q)

Matrix A = 
 [[ 2  4]
 [ 5 -6]]

Transpose of Matrix A = 
 [[ 2  5]
 [ 4 -6]]

Scalar multiplication cA = 
 [[ 10  20]
 [ 25 -30]]

Matrix B = 
 [[ 9 -3]
 [ 3  6]]

Matrix sum S = A + B = 
 [[11  1]
 [ 8  0]]

Matrix product P = A * B = 
 [[ 30  18]
 [ 27 -51]]

Standard matrix product Q = A @ B = 
 [[ 30  18]
 [ 27 -51]]


In [ ]:
import numpy as np
u = np.array([1.1,0.0,3.6,7.2])
print(u)
print('El producto punto del  vector u es',np.dot(u,u))

[1.1 0.  3.6 7.2]
El producto punto del  vector u es 66.01


# Ejercicios

Formule matrices y vectores de distintos tamaños para probar casos en los que no se pueden realizar operaciones entre ellos.

En el capítulo 7 del libro de Boyd usted puede encontrar una amplia variedad de aplicaciones donde el concepto de matriz y sus operaciones cobran especial interés.
[vmls.Boyd](https://vmls-book.stanford.edu/)

# Determinante e Inversa de una Matriz

## Determinante

### Definición
El **determinante** es un número asociado a una matriz cuadrada $A \in \mathbb{R}^{n \times n}$. Puede indicar si la matriz es invertible y describe un **factor de escala** de la transformación lineal que representa. El concepto de transformación lineal lo discutiremos mas adelante.

Para una matriz $2 \times 2$:
$$
A = \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
$$

el determinante se calcula como:
$$
\det(A) = ad - bc.
$$

En general, para una matriz $n\times n$ el cálculo es mucho mas complejo. Debe usted investigar como se calcula
---

### Interpretación geométrica
- En $\mathbb{R}^2$, $|\det(A)|$ representa el área del paralelogramo generado por las columnas de $A$.  
- En $\mathbb{R}^3$, $|\det(A)|$ representa el volumen del paralelepípedo generado por las columnas de $A$.  
- Si $\det(A)=0$,  $A$ **no es invertible**.

---

### Ejemplo de determinante $2 \times 2$
Sea
$$
A = \begin{pmatrix}
2 & 1 \\
3 & 4
\end{pmatrix}
$$

Entonces:
$$
\det(A) = (2)(4) - (1)(3) = 8 - 3 = 5.
$$

Como $\det(A) \neq 0$, la matriz es invertible.

---

## 2. Matriz Inversa

### Definición
La **inversa** de una matriz cuadrada $A$, denotada $A^{-1}$, es una matriz del mismo tamaño $B$ que cumple:
$$
A B = B A = I,
$$

donde $I$ es la **matriz identidad**. La matriz inversa $B$ se denota $A^{-1}$.

Una matriz $A$ es invertible si y sólo si $\det(A) \neq 0$.

---

### Fórmula para matrices $2 \times 2$
Si
$$
A = \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
$$
y $\det(A) \neq 0$, entonces:
$$
A^{-1} = \frac{1}{\det(A)} \begin{pmatrix}
d & -b \\
-c & a
\end{pmatrix}.
$$

---

### Ejemplo de inversa $2 \times 2$
Con
$$
A = \begin{pmatrix}
2 & 1 \\
3 & 4
\end{pmatrix}, \quad \det(A)=5,
$$

tenemos:
$$
A^{-1} = \frac{1}{5} \begin{pmatrix}
4 & -1 \\
-3 & 2
\end{pmatrix}
=
\begin{pmatrix}
\frac{4}{5} & -\frac{1}{5} \\
-\frac{3}{5} & \frac{2}{5}
\end{pmatrix}.
$$

---

### Interpretación geométrica
- En $\mathbb{R}^2$, si $A$ deforma el plano (rotando, escalando, etc.), entonces $A^{-1}$ deshace esa deformación y regresa cada vector a su posición original.

---

### Nota
- No todas las matrices tienen inversa.  
- Si $\det(A)=0$, $A$ es **singular** y **no existe $A^{-1}$**.

### Cálculo de la inversa de una matriz

Hay varias formas de hallar la inversa de una matriz, pero en general es un cálculo propenso a fallar bien sea por errores de cálculo o de redondeo. Investigue que métodos existen para hallar la inversa de una matriz de $n\times n$.


A continuación veremos algunas funciones que nos permiten calcular la inversa y el determinante de una matriz $A$ dada.

In [1]:
import numpy as np

# Definir una matriz (puedes cambiarla)
A = np.array([[2, 1],
              [3, 4]])

print("Matriz A:")
print(A)

# Calcular determinante
detA = np.linalg.det(A)
print(f"\nDeterminante de A: {detA}")

# Verificar si es invertible
if np.isclose(detA, 0):
    print("\nLa matriz NO es invertible (determinante = 0).")
else:
    # Calcular inversa
    A_inv = np.linalg.inv(A)
    print("\nMatriz inversa A⁻¹:")
    print(A_inv)

    # Verificación: A * A⁻¹ debe ser la identidad
    identidad = np.dot(A, A_inv)
    print("\nProducto A * A⁻¹ (debería ser la identidad):")
    print(np.round(identidad, 3))


Matriz A:
[[2 1]
 [3 4]]

Determinante de A: 5.000000000000001

Matriz inversa A⁻¹:
[[ 0.8 -0.2]
 [-0.6  0.4]]

Producto A * A⁻¹ (debería ser la identidad):
[[1. 0.]
 [0. 1.]]


**Ejercicio:** Modifique el código anterior para generar una matriz arbitraria de tamaño $n\times n$, e intente hallar el determinante y la inversa para matrices de tamaño $n=100, 1000$ y $10000$. Qué observa?